public class Main {
    public static void main(String[] args) {
        System.out.println("Hello world!");

//        try {
//            //1st error prone
////            int k = 0;
////            int j = 10/k;
////
////            System.out.println(j);
//
////
////            int[] arr = new int[4];
////
////            for(int i=0;i<=4;i++){
////                System.out.print(arr[i]+" ");
//
////            }
////
////            String str = null;
////
////            str.length();
//
//
//            //Handling of exceptions you have written in the main function
//
//            //coolFunction();
//
//        }
//        catch (ArithmeticException e){
//            System.out.println("A");
//            System.out.println(e.getMessage());
//            //other steps
//        }catch (RuntimeException r){
//            System.out.println("Runtime execption");
//        }

//        catch (Exception e) {
//            throw new RuntimeException(e);
//        }
//        catch (ArithmeticException e){
//
//        }
//        finally { //antim ichha
//            System.out.println("B");
//        }
//
//        System.out.println("C");


    }

//
//    public static void coolFunction() throws Exception{
//
//        int no = 0;
//
//        int newNo = 10/no;
//
//        System.out.println("The newNo is "+newNo);
//    }
//
//    public static void anotherFunction() throws InsufficientBalance {
//
//        int a = 20;
//        if(a==20){
//            throw new InsufficientBalance("D");
//        }
//
//        if(a==40){
//            throw new ArithmeticException("E");
//        }
//    }
}

/*
        How to create a custom exception

// */
//class InsufficientBalance extends Exception {
//
//    InsufficientBalance(String message) {
//        super(message);
//    }
//}

